#TOML doc :D

# AsudServ@gmail.com - mail  H49qFgUDTzSUQFYmoVwf - pass
region=1
logger_path = "logfiles/custLog"
ginLog_path = "logfiles/ginLog"
static_path = "resources/static"
html_path = "resources/html/**"
ssl_path = "ssl"
portHTTP = ":80"
portHTTPS = ":443"   #ip + port основного сервера
server_exchange = ":8080" #ip + port сервера связи с ВПУ

#настройка подключения к тсп серверу ag-server
[tcpServer]
tcpServerAddress = "192.168.115.115"
portLogger=2020
#настройки для постгреса
[database]
db_name = "vpu"
db_password = "162747"
db_user = "postgres"
db_type = "postgres"
db_host = "192.168.115.115"
db_port = "5432"
db_SetMaxOpenConst = 50
db_SetMaxIdleConst = 10
